ethNodeAddr			= "http://127.0.0.1:8500"
bscNodeAddr 		= "http://127.0.0.1:8400"

[tokens]
batchSize 			= 10
batchConcurrency 	= 2


[pairs]
batchSize 			= 10
batchConcurrency 	= 2
blockRange 			= 200


[storage]
driver				= "postgres"


[postgres]
user 				= "postgres"
password 			= "postgres"
host				= "localhost"
port				= "5432"
sslmode 			= "disable"

