name: Go Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get Code
        uses: actions/checkout@v4

      - name: Build
        run: go build ./cmd/*
